### ISSUE TITLE
1. Übungsblatt: UML-Klassen- und -Objektdiagramme Aufgabe 4

### ISSUE THREAD

**Issue by hexahepta** [sweIhm-ws2018-19/skillproject-fr_13#1]

**Comment by OneToughMonkey** [comment]
[aufgabe4.txt](https://github.com/sweIhm-ws2018-19/skillproject-fr_13/files/2495124/aufgabe4.txt)

**Comment by phiebl** [comment]
// Reviewer: phiebl

**Comment by phiebl** [comment]
Review(Java-Code Aufgabe 4) by @phiebl :
-richtige Implementierung von (abstrakten) Klassen mit samt der exakten Methoden und Attribute
-Informationen aus den einzelnen Klassen-Komponenten des vorgegebenen Klassendiagramms wurden korrekt übernommen
-die Zusammenhänge zwischen den Klassen "Konto" und "Kunde" sind im Code enthalten
-die Klasse "Kunde" wurde als abstrakte Klasse implementiert, da die Klassen "Privatkunde" und "Geschäftskunde" beide diese abstrakte Klasse erweitern
