### ISSUE TITLE
2. Übungsblatt: UML-Anwendungsfall-, Aktivitäts- und Sequenz-Diagramme Wiki updaten

### ISSUE THREAD

**Issue by HoferAnton** [sweIhm-ws2018-19/skillproject-fr_13#14]

**Comment by hexahepta** [comment]
Ich habe die .pngs schon mal als Bilder in das Wiki und nicht nur als Hyperlinks eingebunden. Das sollten wir natürlich sobald alle Issues geschlossen und dev entsprechend wieder in den master gemerget wurde aktualiesieren.

**Comment by hexahepta** [comment]
- [ ] Update der pngs
- [ ] Merge von Dev in Master
- [ ] Update der Links im Wiki (auf die Dateien im Master)
