### ISSUE TITLE
Label absprachen

### ISSUE THREAD

**Issue by HoferAnton** [sweIhm-ws2018-19/skillproject-fr_13#15]
Da es momentan verwirrung seitens der Label gibt, würde ich entweder unter den Issues oder im Wiki eine möglichkeit haben zu definieren, wofür bestimmte Label genutzt werden.

> @OneToughMonkey 
> Wie kommst du darauf, von der mindestmöglichen Sichtbarkeit auszugehen?
> ...
> PS: Ich würde das "ready for review" label gerne für den Fall reservieren, dass erstmalig eine Lösung eingetragen wurde und ein Reviewer benötigt wird. So sieht man auf einen Blick in der Issue-Übersicht, welche Issues bearbeitet wurden aber noch keinen Reviewer haben. Mir als Reviewer hilft das Label andererseits wenig weiter, weil ich sowieso standardmäßig über jede Änderung im Issue benachrichtigt werde, wenn ich Asignee bin.

Bisher habe ich das Label "ready for review" genutzt um issues zu markieren, die aus meiner Sicht einer review bedurften.
Zukünftig werde ich dann diese Label auch dafür verwenden um auszudrücken, dass dieses Issue einen Reviewer benötigt.
Ich denke allerdings, dass es nicht sinnvoll ist den Reviewer als Assinee einzutragen, da dann die Grenze zwischen denjenigem der die Aufgabe macht und dem der die Aufgabe reviewed verschwimmt und das möchte ich eigentlich nicht. Außerdem sieht man dann nicht in der Übersicht ob sich was getan hat. Von daher würde ich gerne z.B. Das label "enhancement" dafür verwenden um auszudrücken, dass ein Reviewer drüber geschaut hat und Verbesserungen vorgeschlagen hat. Damit dann die Assignees das Issue schließen können.

**Comment by OneToughMonkey** [comment]
>Ich denke allerdings, dass es nicht sinnvoll ist den Reviewer als Assinee einzutragen, **da dann die Grenze zwischen denjenigem der die Aufgabe macht und dem der die Aufgabe reviewed verschwimmt** und das möchte ich eigentlich nicht.

Verstehe diese Behauptung nicht. Die Assignees selbst sind sich sowieso über ihre Rollen klar. Ein Außenstehender erkennt die Rollen am Verlauf der Zuweisungen, ggf. an dem Kommentar in dem der Reviewer benannt wird und schlimmstenfalls aus dem Diskussionskontext.

>Außerdem sieht man dann nicht in der Übersicht ob sich was getan hat.

Ich finde man braucht der Übersicht auch nur entnehmen, was der Übersicht über den Zustand des Projekts dient. Dafür ist nicht jede kleine Änderung an irgendeinem Issue relevant und zu viele Labels gehen genau auf Kosten der namentlichen Übersichtlichkeit.

Von mir aus machen wir hier noch ein neues Label "reviewer needed", damit man diese wirklich zentral wichtige Information der Übersicht sofort entnehmen kann. Dann kannst du die anderen Label setzen wie du magst, aber ich seh nicht ein für jeden einzelnen Arbeitsschritt auch noch ein Label extra zu setzen.

**Comment by HoferAnton** [comment]
>Verstehe diese Behauptung nicht. Die Assignees selbst sind sich sowieso über ihre Rollen klar. Ein >Außenstehender erkennt die Rollen am Verlauf der Zuweisungen, ggf. an dem Kommentar in dem der >Reviewer benannt wird und schlimmstenfalls aus dem Diskussionskontext.

Definitiv, das ist Richtig. Gemeint hat ich hier halt das Assignees hat nur die sein sollten, die sich dieser Aufgabe angenommen haben und nicht die Reviewer.

Ich denke es macht halt Sinn wenn ich die Teamübersicht öffne und dann anhand eines Labels sehe welche Aufgaben aktuell anstehen. 
Ich weis nicht wie ihr das macht und wenn Ihr da was wisst: her mit ner alternative :+1:  aber momentan geh ich halt wenn ich die Overview aufhab der Reihe nach alle Issues durch und schau halt dann jedes mal nach ob jemand kommentiert hat und ich praktisch wieder was prüfen kann oder mir grad was unklar ist oder ähnliches. Dementsprechend seh ich aber in der Übersicht nicht ob im einzelnen Issue irgend was vorangeht.
Mir ist zwar schon aufgefallen das mir per Mail mitgeteilt wird wenn jemand kommentiert, aber nicht wenn irgendwas geupdated wird und das find ich halt eher suboptimal, und mühsam.
Ich hätte das ganze halt per Labels organisiert, damit man halt ne einfache Übersicht über den aktuellen stand hat, damit meine ich nicht, dass man jetzt Labels aufmachen soll ohne ende ich denke aber ein Label das einem Reviewer anzeigt, das sich was geändert hat mach durchaus Sinn.

**Comment by hexahepta** [comment]
Ein Label das makiert hier gibt es noch keinen Reviewer hallte ich für essentiel damit dies sofort offensichtlich ist, "reviewer needed" ist auch exakt das was ich hierfür vorgeschlagen hätte.

Ich verstehe das es nicht sinnvoll für einzelne Arbeitsschritte ist Label zu vergeben, allerdings denke ich sollen wir uns auf ein paar einigen die den Status des Issues wiedergeben. Dafür gibt es in umfangreichen Task Managment Systemen wie Jira Zustände wie open, assigned, in Development, ready for review, done, closed und ähnliches. Dies mag im momentanen Rahmen noch nach unnötigen Overhead aussehen, sollten wir aber in zukünftigen Aufgaben mit Dingen wie einem Product Backlog und entsprechend vielen Issues zu tun bekommen dürfte es der Übersicht dienlich sein mehr Zustände als open und closed zu haben.
