### ISSUE TITLE
Sprint 0: Anwendungsfalldiagramm

### ISSUE THREAD

**Issue by HoferAnton** [sweIhm-ws2018-19/skillproject-fr_13#20]

**Comment by hexahepta** [comment]
Created and commited [Use Case Diagram](https://github.com/sweIhm-ws2018-19/skillproject-fr_13/blob/dev/UML/ScoreKeeperUseCases)

**Comment by HoferAnton** [comment]
Die Verbindung von Role User zum Usecase besser layouten

**Comment by HoferAnton** [comment]
Nach @phiebl ist der Anwendungsfall start Game Session für eine ganze Spielpartien zuständig. Gibt es einen Anwendungsfall für den Fall das nach den aktuellen eingestellten Parametern für die Spielsession auch eine einzelne  Runde im Spiel gestartet wird? Wo startet der Game Admin eine neue oder die nächste Runde. Ohne alle Parameter neu einzugeben?

So wie sich das Diagramm in Verbindung mit der Beschreibung liest müsste für jede einzelne Runde eine komplett neue Game Session gestartet werden.

**Comment by HoferAnton** [comment]
Ich fände einen zusätzlichen Anwendungsfall "Credits"  bei dem halt wir als Entwickler genannt werden nicht schlecht. Was haltet Ihr so davon?

**Comment by hexahepta** [comment]
Wir können das ganze System auch gerne so bauen das es nur diese drei Funktionen zum verändern von Spieler Punkten gibt. Allerdings bin ich bei erstellen des Diagramms von einem allgemeinen System ausgegangen das möglichst erweiterbar ist. Z. B. dürfte eine Runde Kniffel nur mit Inkrement, Dekrement und Festlegung eines Wertes kaum umsetzbar sein. Dazu fiel mir leider keine bessere Kurzbeschreibung als "Set value change function" ein. Sollten wir ein solches allgemeineres System bauen wollen, könnte ich noch ein Anwendungsfall Diagram für einen spezifischeren Fall (wie etwa Schafkopf) erstellen.

Ich weiß nicht wie @phiebl Spielrunde definiert, für mich ist mit dem Fall "Start Game Session" der Beginn einer in sich geschlossenen Spiel Session gemeint. Sprich werden die Punkte in mehrere Zyklen (üblicherweise als Spielrunden bezeichnet) geändert, findet dies innerhalb einer solchen Session statt. Ich halte einen Anwendungsfall zum erneuten starten einer Session mit dem selben Regelsatz wie in der vorhergehenden überflüssig da dafür entweder einfach das selbe Profil gestartet wird oder die entsprechenden Standard Werte bereits gesetzt sind. Somit scheint mir zwischen dem starten der ersten und einer weiteren Session kein Unterschied in der Funktionalität zu bestehen. 
Das explizite beenden einer Spielrunde sehe ich auch als sinnvoll und werde einen solchen Anwendungsfall sofort ergänzen.

Zum Thema Credits gehe ich mit @OneToughMonkey d'accord und würde es niedrig priorisieren aber der Verfügbarkeit halber füge ich es gern hinzu.

**Comment by hexahepta** [comment]
Bei der Erstellung von Use Cases zu Schafkopf bräuchte ich etwas Hilfe, stellt sich heraus ist deutlich zu lange her das ich mal darin unterwiesen wurde und es scheint nichts hängen geblieben zu sein. Aus Internetfunden wurde ich bis jetzt auch nur bedingt schlau. [Commit](https://github.com/sweIhm-ws2018-19/skillproject-fr_13/commit/47e5e90a6a6c87a1235b3123933c5b367f281d8b)

**Comment by OneToughMonkey** [comment]
> Wir können das ganze System auch gerne so bauen das es nur diese drei Funktionen zum verändern von Spieler Punkten gibt. Allerdings bin ich bei erstellen des Diagramms von einem allgemeinen System ausgegangen das möglichst erweiterbar ist. Z. B. dürfte eine Runde Kniffel nur mit Inkrement, Dekrement und Festlegung eines Wertes kaum umsetzbar sein. Dazu fiel mir leider keine bessere Kurzbeschreibung als "Set value change function" ein.

Ich glaube sämtliche Punkte-Regeln für ein Spiel wie Kniffel per Spracheingabe zu definieren würde jeden Nutzer an die Grenzen seiner Geduld bringen.  Ganz zu schweigen vom Programmierer der die Spieldefinition _so_ allgemein ermöglichen soll.

Bei sowas wie Kniffel hätte ich gedacht, dass das (wenn überhaupt) nur vorprogrammiert verfügbar gemacht wird.

> Ich weiß nicht wie @phiebl Spielrunde definiert, für mich ist mit dem Fall "Start Game Session" der Beginn einer in sich geschlossenen Spiel Session gemeint. Sprich werden die Punkte in mehrere Zyklen (üblicherweise als Spielrunden bezeichnet) geändert, findet dies innerhalb einer solchen Session statt. Ich halte einen Anwendungsfall zum erneuten starten einer Session mit dem selben Regelsatz wie in der vorhergehenden überflüssig da dafür entweder einfach das selbe Profil gestartet wird oder die entsprechenden Standard Werte bereits gesetzt sind. Somit scheint mir zwischen dem starten der ersten und einer weiteren Session kein Unterschied in der Funktionalität zu bestehen.

So wie ich das verstanden hatte, geht es eher darum, dass man oft nach Ende eines Spiels, in dem Sinne, dass ein Sieger feststeht, nochmal das gleiche Spiel, mit zurückgesetzten Punkten, spielen will. Aktuell müsste man dann halt erst wieder das entsprechende Profil auswählen, damit man dann das Spiel wieder starten kann. Kann vielleicht etwas nervig sein.

Man könnte das sonst evtl. auch dadurch bewältigen, dass Alexa generell beim Start einer Game Session vom  zuletzt gesetzten Spielprofil ausgeht.

>Bei der Erstellung von Use Cases zu Schafkopf bräuchte ich etwas Hilfe, stellt sich heraus ist deutlich zu lange her das ich mal darin unterwiesen wurde und es scheint nichts hängen geblieben zu sein. Aus Internetfunden wurde ich bis jetzt auch nur bedingt schlau. 
Hab da leider auch keine Ahnung mehr, ist mehr als 10 Jahre her dass ich das mal gelernt hab.

**Comment by hexahepta** [comment]
> So wie ich das verstanden hatte, geht es eher darum, dass man oft nach Ende eines Spiels, in dem Sinne, dass ein Sieger feststeht, nochmal das gleiche Spiel, mit zurückgesetzten Punkten, spielen will. Aktuell müsste man dann halt erst wieder das entsprechende Profil auswählen, damit man dann das Spiel wieder starten kann. Kann vielleicht etwas nervig sein.
> 
> Man könnte das sonst evtl. auch dadurch bewältigen, dass Alexa generell beim Start einer Game Session vom zuletzt gesetzten Spielprofil ausgeht.

Ja finde ich auch vernünftig wenn man ein eingestelltes Profil nicht erneut auswählen muss bei start einer neuen Session.

> Ich glaube sämtliche Punkte-Regeln für ein Spiel wie Kniffel per Spracheingabe zu definieren würde jeden Nutzer an die Grenzen seiner Geduld bringen. Ganz zu schweigen vom Programmierer der die Spieldefinition so allgemein ermöglichen soll.
> 
> Bei sowas wie Kniffel hätte ich gedacht, dass das (wenn überhaupt) nur vorprogrammiert verfügbar gemacht wird.

Genau das wollte ich damit ausdrücken, die Möglichkeit der expliziten Wahl einer "Change value function" ist nur zur Nutzung von Funktionen für ein Spiel gedacht das nicht als (programmiertes) Profil vorliegt. So dass etwa ein Kniffel gespielt werden könnte wenn jemand dafür Software schreibt und diese in das System einbindet. Ich wollte damit nur sagen das wenn wir nur fest definierte Funktionen (z.B. inkrement, dekrement, set) erstellen nicht die Möglichkeit besteht komplexeres Regelwerk in unserem System abzubilden. 

Sprich ich habe versucht das System erweiterbar zu modelieren so das etwa Kniffel nachträglich noch als Profil programmiert werden kann. Die Funktionen zum verarbeiten von Punkten sollen innerhalb des Systems nur von einem Entwickler erstellt werden können und von dem "Game Admin" ausgewählt werden.

**Comment by hexahepta** [comment]
Anstelle des Subsystems zu Schafkopf habe ich jetzt erst einmal ein Grund Profil mit den Funktionen Punkte zu setzen, addieren und subtrahieren erstellt.

**Comment by OneToughMonkey** [comment]
> Ja finde ich auch vernünftig wenn man ein eingestelltes Profil nicht erneut auswählen muss bei start einer neuen Session.

Ok, dann werde ich das so in mein Review der Anwendungsfallbeschreibung eingehen lassen.

> Genau das wollte ich damit ausdrücken, die Möglichkeit der expliziten Wahl einer "Change value function" ist nur zur Nutzung von Funktionen für ein Spiel gedacht das nicht als (programmiertes) Profil vorliegt. So dass etwa ein Kniffel gespielt werden könnte wenn jemand dafür Software schreibt und diese in das System einbindet. Ich wollte damit nur sagen das wenn wir nur fest definierte Funktionen (z.B. inkrement, dekrement, set) erstellen nicht die Möglichkeit besteht komplexeres Regelwerk in unserem System abzubilden.
> 
> Sprich ich habe versucht das System erweiterbar zu modelieren so das etwa Kniffel nachträglich noch als Profil programmiert werden kann. Die Funktionen zum verarbeiten von Punkten sollen innerhalb des Systems nur von einem Entwickler erstellt werden können und von dem "Game Admin" ausgewählt werden.

Hm... ich bin mir immer noch nicht ganz sicher, ob ich dich richtig verstehe.

Ich hatte mir das so vorgestellt, dass ein "Game Profile" entweder vollständig (also inklusive default value und ggf. komplexeren "change value" Funktionen) vordefiniert ausgewählt wird, oder mit eingeschränkter Freiheit selbst definiert werden kann.

In meinem [getstoryline-Prototyp](https://app.invocable.com/shared/projects/2cb7131f08bfb6cf5ec201b56c716d962a7bbdd2) habe ich folgende Schritte für ein Mindestmaß an Flexibilität in der Definition eigener Spielprofile im Rahmen "simpler" Regelwerke durch den Nutzer identifiziert:
- Startpunktezahl festlegen
- Siegpunktezahl festlegen 
    **oder** Siegpunktezahl offenlassen und dafür zusätzlich definieren, ob es um Punktemaximierung oder Punkteminimierung geht

Nach diesem Modell würde sich nicht nur die Implementation sondern auch die Auswahl entsprechender "Value change" Funktionen zur Umsetzung komplexerer Regelwerke rein in den (zukünftigen) Verantwortungsbereich der Entwickler verlagern.

**Comment by hexahepta** [comment]
Genau deshalb habe ich im Diagram neben der Auswahl des Profils auch die beiden Use Cases zum setzten der Start Punkte und Auswahl der Funktion zur Veränderung dieser. Ziemlich genau wie du es beschreibts. Das ist durchaus so gedacht das du entweder ein Profil wählst oder das durch nutzen dieser Funktionen selbst definierts.
