### ISSUE TITLE
Sprint 0: Beschreibung der Anwendungsfälle

### ISSUE THREAD

**Issue by HoferAnton** [sweIhm-ws2018-19/skillproject-fr_13#21]

**Comment by OneToughMonkey** [comment]
Reviewer: @OneToughMonkey

**Comment by OneToughMonkey** [comment]
Hast du was dagegen wenn ich das auf Google Docs hochlade und meine Anmerkungen direkt im Dokument mache? Wenn du nix dagegen hast, hast du auch nen Google Account?

**Comment by phiebl** [comment]
Kannst du gerne machen und ja ich habe einen Google Account.

**Comment by OneToughMonkey** [comment]
Ich bin krank und schaffe es heute leider nicht mehr die nötige Konzentration, um weiter an dem Projekt zu arbeiten, aufzubringen.

Ziehe mich daher vorerst als Reviewer wieder zurück.

**Comment by phiebl** [comment]
Wollen wir das ggf. aufteilen?

**Comment by hexahepta** [comment]
Können wir von mir aus machen.

**Comment by hexahepta** [comment]
Ich übernehme die bestehenden schon einmal ins Wiki. Wenn du dann noch welche übrig hast sag welche ich davon übernehmen soll.

**Comment by phiebl** [comment]
Mach ich. Dann würde ich noch die übrigen Use-Cases aus dem <ScoreKeeper> übernehmen. Die aus dem Subsystem kannst du dir dann ja mal anschauen.

**Comment by phiebl** [comment]
Noch eine Frage: was genau verstehst du unter "Get credits"? Ich frag nur, damit es keine Missverständnisse gibt.

**Comment by hexahepta** [comment]
Da sollen einfach die Credits sprich Angaben zu den Entwicklern gemacht werden. Wie bei nem Kino Film am Ende oder jedem Computerspiel.

**Comment by phiebl** [comment]
Achso ... danke 👍

**Comment by hexahepta** [comment]
Gut ich nehm mir dann jetzt mal Increase score vor.

**Comment by phiebl** [comment]
Ich habe jetzt die zwei fehlenden Anwendungsfallbeschreibungen (End game session, get credits) fertig.

**Comment by hexahepta** [comment]
Ok ich habe Increase score fertig und mache gerade decrease score. Schreibst du dann noch schnell als UC10 Set Score?

**Comment by hexahepta** [comment]
Increase und Decrease Score sind schon im Wiki. Soll ich noch die Ergänzungen einfügen?
