### ISSUE TITLE
Sprint 0: Beschreibung der User Stories

### ISSUE THREAD

**Issue by HoferAnton** [sweIhm-ws2018-19/skillproject-fr_13#23]

**Comment by OneToughMonkey** [comment]
Warum nicht nach dem Muster "Als <Benutzerrolle> will ich <das Ziel>[, um <Nutzen>]"?

**Comment by HoferAnton** [comment]
Benötige Feedback bezüglich weiterer User-Stories die ich übersehen hab.
@OneToughMonkey Wird noch überarbeitet.

**Comment by HoferAnton** [comment]
@OneToughMonkey Eigentlich weil ich mich von der 2. Quelle auf Moodle zum Thema userstories leiten hab lassen.

**Comment by hexahepta** [comment]
Bis auf das Issue #29 passt das alles für mich. Bei "Score Keeper Ein Spiel spielen" sieht mir zu komplex für eine einzelne User Storie. Ich denke es wäre sinnvoll diese noch etwas zu unterteilen.

**Comment by phiebl** [comment]
Teilen wir die User-Stories dann auf? Wenn ja wer schreibt dann welche?

**Comment by hexahepta** [comment]
Ich habe in #29 mal eine Beschreibung bei gefügt wie ich mir das da so dachte und ein neues Issue als Ergänzung #33

**Comment by OneToughMonkey** [comment]
Am Rande: Mir wurde von anderen Gruppen mitgeteilt, dass Frau Socher ihnen gegenüber angegeben hat, dass sie mindestens etwa 20 User Stories erwartet. Vielleicht sollten wir schauen, ob sich manche User-Stories noch feiner unterteilen lassen?

**Comment by hexahepta** [comment]
Ich versuche die User Stories noch etwas mehr zu abstrahieren, aber so 20 Stück könnte glaub ich schwer werden.

**Comment by OneToughMonkey** [comment]
Ist wie jetzt auch nur aus dritter Hand und vielleicht auch vom Projekt abhängig... wollte damit nur bemerken dass als Richtlinie wohl "umso mehr umso besser" gilt. 

Wir schauen jetzt einfach mal, dass wir in der restlichen Zeit noch unser bestmögliches Ergebnis liefern, wird dann schon passen, aber ich finde wir sollten uns morgen gemeinsam auch nochmal überlegen, wie wir uns im nächsten Sprint zeitlich besser organisieren können.
