### ISSUE TITLE
Sprint 0: Fachklassenmodell (Analyseklassenmodell)

### ISSUE THREAD

**Issue by HoferAnton** [sweIhm-ws2018-19/skillproject-fr_13#25]

**Comment by HoferAnton** [comment]
@hexahepta, @OneToughMonkey , @phiebl Was denkt Ihr was Sie hier haben will?

**Comment by OneToughMonkey** [comment]
Kurzes Update: Dachte eigentlich ich wär fast fertig, aber bin dann drauf gekommen, dass in der UML keine Map-Datentypen (wie ich sie für unsere Punktetabellen vorgsehen hatte) definiert sind.

**Comment by OneToughMonkey** [comment]
Ja, hab mir gerade nochmal den Buchausschnitt dazu durchgelesen und wahrscheinlich ist es wirklich zu detailliert geworden.... Werde es jetzt nochmal zurechtstutzen, aber die ausführlichere Version auch hochladen, vielleicht wird die uns ja später intern noch nützlich sein.

Fazit des Tages ist jedenfalls, dass jeder Programmierer der freiwillig Diagramme nach dogmatischer Auslegung der UML-Syntax zeichnet massiv masochistische Veranlagungen haben muss...

**Comment by OneToughMonkey** [comment]
Wobei sie ja andererseits selber bei der Lieblingsfarbe im Beispiel auf den Folien wieder den fast maximalen Detailgrad verwendet hat...

**Comment by HoferAnton** [comment]
@OneToughMonkey  Ja schon, aber sie hat selber in der Vorlesung gesagt dass das eig schon fast zu viel ist, kann man machen, aber nach Ihr stünde da sonst halt garnix, Sie wollte uns aber zeigen das da durchaus was hinkommt. Außer ich erinnere mich falsch.

**Comment by HoferAnton** [comment]
Muss nicht auch sowas wie ein Controller existieren, damit man auswählen kann was man grade machen will, ob man jetzt spielen will oder was mit nem Highscore machen will?

**Comment by HoferAnton** [comment]
Im generellen sollten im Fachklassenmodell nicht alle Klassen connected sein?

**Comment by OneToughMonkey** [comment]
> @OneToughMonkey Ja schon, aber sie hat selber in der Vorlesung gesagt dass das eig schon fast zu viel ist, kann man machen, aber nach Ihr stünde da sonst halt garnix, Sie wollte uns aber zeigen das da durchaus was hinkommt. Außer ich erinnere mich falsch.
Also kürzen - oder?

> Muss nicht auch sowas wie ein Controller existieren, damit man auswählen kann was man grade machen will, ob man jetzt spielen will oder was mit nem Highscore machen will?
Bildet für mich keine Daten/Gegenstände, die spezifisch für das "Geschäftssystem" (im Kontrast zum Softwaresystem) sind ab bzw. ist zu allgemein für das Fachklassenmodell.

> Im generellen sollten im Fachklassenmodell nicht alle Klassen connected sein?
Wie kommst du denn darauf?

**Comment by HoferAnton** [comment]
Weil es ja ein zusammenhängender Skill ist und wir unterschiedliche teilbereiche haben?

**Comment by OneToughMonkey** [comment]
Ja aber gerade wenn man nicht jedes Detail des Systems repräsentiert können sich da doch leicht Lücken ergeben, oder?

Überarbeitete und drastisch minimalisierte Version:

https://github.com/sweIhm-ws2018-19/skillproject-fr_13/blob/08d5925d33ee8e16c4a8ca1705004732351ffb8e/ScoreKeeper/Design/Fachklassenmodell.png

**Comment by HoferAnton** [comment]
Moment..... Ich wollte nicht das du es zwingend kürzt.... SRY  ich denke das ursprüngliche Diagramm sollte schon passen.
Was ich meinte ist das hier nicht zwingend alles festgelegt sein soll. Sondern nur wovon man schon weis dass es so sein soll.

**Comment by OneToughMonkey** [comment]
Ne ich glaub du hast schon recht, das erste war zu ausführlich. Hab das alte als XML im Repository mal drin gelassen aber das minimalisierte jetzt im Wiki verlinkt.

**Comment by HoferAnton** [comment]
ok, ich bin mir nicht sicher, was ich so bei Chris gesehen hab, die haben das eher wie die ausführliche Version
