### ISSUE TITLE
Sprint 0: Struktur des Repository anpassen

### ISSUE THREAD

**Issue by OneToughMonkey** [sweIhm-ws2018-19/skillproject-fr_13#26]
Die Dateien zu Sprint 0 alle weiterhin einfach in den UML-Ordner zu schmeissen halte ich mittelfristig für Quatsch, weil a) es sich um eine neue Klasse von Aufgaben handelt, b) es sinnvoll wäre die Dateien zu unserem großen Projekt schnell finden zu können und c) nicht nur UML-Dateien enthalten sind.

Ich würde hier eine radikale Umstrukturierung vorschlagen:

- Die Quelldateien zum Colorpicker alle in ein Verzeichnis im Root des Repository
- Ein neues Verzeichnis für den Score Keeper im Root des Repository
- (Mindestens) 2 Unterverzeichnisse unter Score Keeper, eines für die gesammelten Dateien zu Analyse/Design, eines für das eigentliche Java-Projekt

Bitte um Feedback.

**Comment by HoferAnton** [comment]
Finde ich Sinnvoll im Hinblick auf den nächsten Sprint. Außerdem sollten wir mal wieder dev mergen das kann man dann Ja in einem Zug machen?

**Comment by hexahepta** [comment]
Eine Umstrukturierung zum erreichen besser Übersichtlichkeit im Repository erscheint auch mir sinnvoll. Kümmert sich schon jemand darum? Falls nein würde ich das übernehmen.

**Comment by hexahepta** [comment]
Ich habe jetzt mal eine Umstrukturierung vorgenommen. Hoffe das entspricht so eurer Vorstellung.

**Comment by OneToughMonkey** [comment]
Passt fürs erste auf jeden Fall.
