### ISSUE TITLE
Score Keeper Skill Start

### ISSUE THREAD

**Issue by HoferAnton** [sweIhm-ws2018-19/skillproject-fr_13#27]

**Comment by hexahepta** [comment]
Als Nutzer möchte ich den Alexa Skill Score Keeper starten können.

Akzeptiert wird wenn:

- Ein Nutzer den Skill starten kann

**Comment by OneToughMonkey** [comment]
Ich habe den Skill inzwischen mit allen für das Sprintziel als relevanten markierten User Stories recht stabil zum laufen gebracht. Der Sourcecode liegt in meinem Branch "monkeydev" und die Implementation kann über den Alexa Developer Console Gruppenaccount getestet werden.

**Comment by phiebl** [comment]
Der LaunchRequestHandler ermöglicht es, dass der Skill entweder neu gestartet oder fortgeführt werden kann. Dies wird durch die persistente Speicherung der zugehörigen Attribute ermöglicht. Bei der Ausführung des Skills in der Alexa Developer Console kann der Skill gemäß der Vorgabe korrekt gestartet werden.
