### ISSUE TITLE
Score Keeper Ein Spiel starten

### ISSUE THREAD

**Issue by HoferAnton** [sweIhm-ws2018-19/skillproject-fr_13#29]

**Comment by OneToughMonkey** [comment]
Ich habe den Skill inzwischen mit allen für das Sprintziel als relevanten markierten User Stories recht stabil zum laufen gebracht. Der Sourcecode liegt in meinem Branch "monkeydev" und die Implementation kann über den Alexa Developer Console Gruppenaccount getestet werden.

**Comment by phiebl** [comment]
Reviewer @phiebl:

**Comment by phiebl** [comment]
Mit dem StartGameSessionIntentHandler lässt sich ein neues Spiel starten. Wenn bereits eine Spielsitzung im Gange ist, wird der Spieler vom Skill daraufhingewiesen, dass die laufende Sitzung zuerst beendet werden muss, was im IntententHandler mittels persistenter Speicherung dieser Information vermerkt ist. Falls eine neue Spielsitzung gestartet werden soll/kann wird für die neue Spielsitzung eine neue HashMap aus String- in Verbindung mit Longobjekten angelegt und persistent gespeichert. Der Skill kann ein Spiel mit mehreren möglichen Eingaben starten.
