### ISSUE TITLE
Abschluss Übungsblatt Klassen-/Objektdiagramme

### ISSUE THREAD

**Issue by OneToughMonkey** [sweIhm-ws2018-19/skillproject-fr_13#3]
Folgende Schritte sind noch zu erledigen, wenn das Issue zu Aufgabe 5 geschlossen wurde:

- Branch dev mit master mergen
- Lösungen Aufgabe 4 und 5 auf _einer_ Wiki-Seite verlinken und den Link zur Wiki-Seite auf Moodle abgeben: **Die Lösung muss auf der Wiki-Seite, die in Moodle verlinkt ist, klar erkennbar sein. Es werden keine Zip Files oder im git Repository versteckten Files gesucht.**

Freiwillige vor :)

**Comment by HoferAnton** [comment]
@OneToughMonkey ich habe im Wiki die Aufgabe 5 schonmal verlinkt, wenn sich da nochmal was ändert müsste man den Link halt wieder ändern. Bei Aufgabe 4 muss der merge erfolgen bevor man verlinken kann, aber die Plazierung des Links ist schon eingerichtet.

**Comment by hexahepta** [comment]
- [ ] Merge dev in master

- [ ] Link zur Lösung von Aufgabe 4 ins Wiki

- [ ] Link zur Lösung von Aufgabe 5 ins Wiki

**Comment by OneToughMonkey** [comment]
- Wiki überarbeitet
- Gebe den Link https://github.com/sweIhm-ws2018-19/skillproject-fr_13/wiki/Assignment-1:-UML-object--and-class-diagrams um 22:00 ab, wenn bis dahin keine Einwände kommen

**Comment by hexahepta** [comment]
Sehr schön, habe das leider gerade zu spät gelesen und schon einmal als Abgabe hinzugefügt.

**Comment by OneToughMonkey** [comment]
Nvm, hab nicht dran gedacht dass man die Abgabe ja eh noch bearbeiten kann ;)
