### ISSUE TITLE
Score Keeper Hilfe

### ISSUE THREAD

**Issue by HoferAnton** [sweIhm-ws2018-19/skillproject-fr_13#31]
Als Nutzer habe ich die Übersicht über das Aktuelle geschehen verloren und möchte diese zurückgewinnen, um mich im Menü weiter fort zu bewegen. Dabei unterstützt mich die Hilfefunktion, die ich jederzeit fragen kann.

Akzeptiert wenn:
- Die Hilfefunktion aus jedem Menüpunkt ausprechbar ist
- Die Hilfefunktion über den aktuellen Stand der App Auskunft geben kann

**Comment by OneToughMonkey** [comment]
Die Hilfe-Funktion wurde im Rahmen der Implementation des Spielprofils "Zehntausend" adäquat angepasst.
