### ISSUE TITLE
Score Keeper Ein Spiel beenden

### ISSUE THREAD

**Issue by hexahepta** [sweIhm-ws2018-19/skillproject-fr_13#33]
Als Spielleiter möchte ich eine laufende Spielsitzung beenden können, um ein neues Spiel starten zu können.

Akzeptiert wird wenn:

- Eine laufende Spielsitzung beendet werden kann
- Nach dem beenden einer Sitzung eine neue gestartet werden kann
- Automatisierte Unit Tests für die User Story implementiert wurden
- Es ein UML Diagramm zur Idee der Implementation der User Story gibt

**Comment by OneToughMonkey** [comment]
Ich habe den Skill inzwischen mit allen für das Sprintziel als relevanten markierten User Stories recht stabil zum laufen gebracht. Der Sourcecode liegt in meinem Branch "monkeydev" und die Implementation kann über den Alexa Developer Console Gruppenaccount getestet werden.

**Comment by phiebl** [comment]
Reviewer @phiebl:

**Comment by phiebl** [comment]
Der EndGameSessionIntentHandler kann den Skill beenden. Dabei kann der Skill unterscheiden, ob ein laufendes Spiel beendet werden kann oder kein Spiel läuft. Die Daten eines laufenden Spiels werden persistent in der Alexa DB gespeichert. Beim Testen des Skills in der Developer Console hat das Beenden eines laufenden Spiels sowie die Rückgabe der Information, dass kein Spiel läuft, funktioniert.
