### ISSUE TITLE
Score Keeper Punktestand setzen

### ISSUE THREAD

**Issue by hexahepta** [sweIhm-ws2018-19/skillproject-fr_13#34]
Als Nutzer möchte ich den einem gegebenen Spielteilnehmernamen zugeordneten Punktestand festlegen können.

Akzeptiert wird wenn:

- Der Punktestand für einen beim Namen genannten Spielteilnehmer festgelegt werden kann
- Eine akustische Bestätigung der Festlegung der Punkte durch Alexa erfolgt
- Automatisierte Unit Tests für die User Story implementiert wurden
- Es ein UML Diagramm zur Idee der Implementation der User Story gibt

**Comment by OneToughMonkey** [comment]
Bin gerade dahintergekomen, dass eIne Session mit einem Alexa Skill prinzipiell eigentlich nicht über mehr als ein paar Sekunden ohne Konversation aufrecht erhalten werden kann... da müssen wir uns was überlegen.

**Comment by hexahepta** [comment]
Dann müssen wir das ganze System als Webservice bauen, oder aber laufende Spielsitzungen persistieren.

**Comment by OneToughMonkey** [comment]
Alles persistent zu machen wär auch meine erste Idee gewesen. Macht es halt etwas weniger komfortabel, wenn man den Skill erst immer wieder öffnen muss, aber ist wahrscheinlich die einfachste Lösung.

Wie du dir vorstellst das über einen Webservice zu lösen müsstest du mir genauer erklären.

**Comment by hexahepta** [comment]
Naja wenn ich dich richtig verstehe können wir unser System nicht lange aufrecht erhalten, sprich wir müssen den Zustand irgendwie anders sicher und dann immer wieder da rein laden. Dazu fällt mir eben entweder Persistierung direkt im System ein oder dieses auszulagern und als nen stateful Server laufen lassen. So dass der Skill unabhängig von dem System läuft und als reine Schnittstelle dient.

**Comment by OneToughMonkey** [comment]
Jetzt geht es plötzlich doch...

**Comment by OneToughMonkey** [comment]
Ich habe den Skill inzwischen mit allen für das Sprintziel als relevanten markierten User Stories recht stabil zum laufen gebracht. Der Sourcecode liegt in meinem Branch "monkeydev" und die Implementation kann über den Alexa Developer Console Gruppenaccount getestet werden.

**Comment by hexahepta** [comment]
Beim Vorführen fiel auf das ein Eintragen von Negativen Punkten nicht richtig erkannt wurde. Sogar das gennante minus zum namen hinzugefügt wurde statt an die Punkte.

**Comment by phiebl** [comment]
Reviewer @phiebl:

**Comment by phiebl** [comment]
Die User-Story Punktestand setzen setzt sich zusammen aus den Intents SetPlayerScore, SetNegativePlayerScore und SetPositivePlayerScore. Der SetPlayerScoreIntentHandler kann einen Spielstand einem Spieler zuweisen, den User darauf hinweisen, dass zuerst eine Runde gestartet werden muss oder eine Remprompt Message ausgeben, wenn die beiden vorherigen Ereignisse nicht möglich sind. Zur Bestätigung kann der Skill ein Confirmation/No-Session/Reprompt Message ausgeben. Mit den SetPositive- und SetNegativePlayerScroreIntentHandlern können die Spielstände erhöht und verringert werden. Beim Testen des Skills haben die Punktezuordnung zu mehreren unterschiedlichen Spielern sowie die Punktestandveränderung funktioniert.
