### ISSUE TITLE
Score Keeper Punkte addieren

### ISSUE THREAD

**Issue by hexahepta** [sweIhm-ws2018-19/skillproject-fr_13#35]
Als Spieler möchte ich meinen Punktestand um einen bestimmten Wert erhöhen können.

Akzeptiert wird wenn:

- Ein spieler seinen Punktestand erhöhen kann

**Comment by hexahepta** [comment]
Reviewer: @hexahepta

**Comment by hexahepta** [comment]
Wenn die Methode parsePoints(String points) jetzt nicht mehr nur die Zeichenkette in eine Zahl übersetzt und dabei noch das Vorzeichen beachtet, wäre eine andere Bezeichnung etwa modifyPoints vlt. angebracht.

Die Akzeptanzekriterien werden voll erfüllt.

**Comment by OneToughMonkey** [comment]
Stimme dir grundsätzlich zu. "modify" scheint mir aber dann aber für die beiden ursprünglichen Klassen nicht ganz zutreffend. vllt. calculatePoints?

**Comment by hexahepta** [comment]
Ja das klingt gut sonnst könnte man darüber nachdenken ob man das aufteilt. Aber wenn die Methode nicht komplexer wird als sie jetzt ist würde ichs bei einer lassen.

**Comment by OneToughMonkey** [comment]
alles klar, dann machen wir das so
