### ISSUE TITLE
Score Keeper Skill Ende

### ISSUE THREAD

**Issue by hexahepta** [sweIhm-ws2018-19/skillproject-fr_13#39]
Als Nutzer möchte ich den Alexa Skill Score Keeper beenden können, um auch andere Skills nutzen zu können.

Akzeptiert wird wenn:

- Ein Nutzer den Skill beenden kann
- Automatisierte Unit Tests für die User Story implementiert wurden
- Es ein UML Diagramm zur Idee der Implementation der User Story gibt

**Comment by OneToughMonkey** [comment]
Ich habe den Skill inzwischen mit allen für das Sprintziel als relevanten markierten User Stories recht stabil zum laufen gebracht. Der Sourcecode liegt in meinem Branch "monkeydev" und die Implementation kann über den Alexa Developer Console Gruppenaccount getestet werden.

**Comment by phiebl** [comment]
Reviewer @phiebl:
