### ISSUE TITLE
Sprint 0: Abschluss Wiki & Abgabe

### ISSUE THREAD

**Issue by OneToughMonkey** [sweIhm-ws2018-19/skillproject-fr_13#40]
Für Absprachen zum Abschluss des Sprint.

Konkret ist mir gerade aufgefallen: Sollte die SkillKeeper-Sytemidee nicht die neue _Startseite_ des Wikis sein? Darf ich nochmal überarbeiten oder ist da grad wer anders dran?

**Comment by OneToughMonkey** [comment]
Keine Antwort ist auch eine Antwort ;)
Mach das jetzt...

**Comment by HoferAnton** [comment]
Wenn du da ne konkrete Idee hast von mir aus gern.

**Comment by HoferAnton** [comment]
Der Service heißt nicht mehr get story line sondern invocable?

Ok, ja kann man so machen mit dem Wiki was ich bis jetzt gesehen hab.

**Comment by OneToughMonkey** [comment]
ja, haben den namen geändert

**Comment by OneToughMonkey** [comment]
Werde jetzt die Repositorys mergen, den Link auf Moodle abgeben und dann auch die restlichen Issues schließen wenn sich dort bis dahin nix mehr tut.

**Comment by OneToughMonkey** [comment]
...und gute Nacht! :)
