### ISSUE TITLE
Score Keeper Punktestand aller Spielteilnehmer ausgeben

### ISSUE THREAD

**Issue by OneToughMonkey** [sweIhm-ws2018-19/skillproject-fr_13#41]
Als Nutzer möchte ich mir den aktuellen Punktestand aller Spielteilnehmer ausgeben lassen.

Akzeptiert wird wenn:
- Alle aktuell gespeicherten Spielteilnehmernamen und zugehörigen Punktestände auf Aufforderung ausgegeben werden
- Automatisierte Unit Tests für die User Story implementiert wurden
- Es ein UML Diagramm zur Idee der Implementation der User Story gibt

**Comment by OneToughMonkey** [comment]
Ich habe den Skill inzwischen mit allen für das Sprintziel als relevanten markierten User Stories recht stabil zum laufen gebracht. Der Sourcecode liegt in meinem Branch "monkeydev" und die Implementation kann über den Alexa Developer Console Gruppenaccount getestet werden.

**Comment by phiebl** [comment]
Reviewer @phiebl:

**Comment by phiebl** [comment]
Für die ausgabe der Punktestände der einzelnen Spieler ist der GetPlayerScoreIntentHandler zuständig. Falls keine Punkte vorhanden sind wird ein entsprechender Hinweis ausgegeben. Ansonsten wird der Punktstand aller Teilnehmer ausgegeben. Die Punktestände werden persisten in einer Alexa DB gespeichert. Beim Test in der Developer Console konnten die Spielstände zum korrekten Spieler zugewiesen und dementsprechend ausgegeben werden. Außerdem hat die pesistente Speicherung nach z.B. einem Abbruch des Skills gut funktioniert.
