### ISSUE TITLE
Score Keeper Spieler hinzufügen

### ISSUE THREAD

**Issue by OneToughMonkey** [sweIhm-ws2018-19/skillproject-fr_13#42]
Als Game Admin möchte ich einem laufenden Spiel Spielteilnehmer mit Namen hinzufügen können. Den neu hinzugefügten Spielteilnehmern wird dabei automatisch die im Spielprofil definierte Startpunktezahl zugeteilt.

Akzeptiert wird wenn:
- Dem laufenden Spiel Spielteilnehmer mit Namen hinzugefügt werden können
- Eine akustische Bestätigung über das Hinzufügen von Alexa erfolgt
- Neue Spielteilnehmer mit dem im Spielprofil definierten Punktestand starten

**Comment by HoferAnton** [comment]
Die Datenstruktur in der Datenbank muss evtl. gemeinsam mit den Settern und Gettern von Spielerpunkten überarbeitet werden.

**Comment by OneToughMonkey** [comment]
Reviewer: @OneToughMonkey 

Schaut gut aus, solide Arbeit. Ich hab ein paar kleine ästhetische Änderungen am Code gemacht die ich jetzt dann noch schnell pushe und dann mach ich mich ans Klassendiagramm.
