### ISSUE TITLE
README aktualisieren

### ISSUE THREAD

**Issue by OneToughMonkey** [sweIhm-ws2018-19/skillproject-fr_13#45]
"Aktualisieren Sie das README.md Ihres Github Repositories. Schreiben Sie den Namen und eine kurze Beschreibung Ihres Skills."

**Comment by hexahepta** [comment]
Sorry mein Internet hat gerade einige Downs. Wenns nicht wieder abbricht hab ichs gleich.

**Comment by OneToughMonkey** [comment]
hast ja noch mindestens bis 23:55, wollt nur wissen ob Du dich drum kümmerst. danke.

**Comment by hexahepta** [comment]
README.md mit einer kurzen Beschreibung geupdatet.

**Comment by HoferAnton** [comment]
1. Ich würde das ganze evtl. etwas ausführlicher machen
sowas in der Richtung:

# Score Keeper
Ein Alexa Skill, der für die Sicherung von Punkteständen für zahlreiche Gesellschaftsspiele wie Schafkopf, Monopoly oder die Siedler von Catan.

Sprachbefehle auf die Alexa dabei reagiert, sind in an der natürlichen Sprache angelehnt und ermöglichen es den Spielfluss in netter Gesellschaft aufrecht zu erhalten.

Dabei sind Typische Befehle des Alexa Skill:
...

Dieses Softwareprojekt ist im Zuge des Praktikums für Softwareengineering als studentisches Projekt der Hochschule München entstanden.
Der Alexa Skill kann momentan Spielern Datenwerte zuordnen, die Datenwerte für die Spieler speichern und die gespeicherten Daten wieder in Form von Sprachnachrichten ausgeben. In den kommenden erweiterungen dieses Softwareprojekts wird dieses Projekt weiter ausgebaut und um weitere Features ergänzt.

**Comment by hexahepta** [comment]
Danke deine Idee ist ziemlich gut. Hab sie mit meinem etwas vermischt.

**Comment by HoferAnton** [comment]
Rechtschreibfehler:
fähgien -> fähigen

**Comment by HoferAnton** [comment]
... Erweiterungen dieses Softwareprojekts wird der Skill um ...

**Comment by hexahepta** [comment]
Danke. Ist ausgebessert.
