### ISSUE TITLE
Score Keeper Tests

### ISSUE THREAD

**Issue by HoferAnton** [sweIhm-ws2018-19/skillproject-fr_13#48]
Ich hab mich mal etwas umgeschaut wie die Skills im Backend getestet werden.
Dabei hab ich mal die javadoc betrachtet:
[Javadoc von Amazon zu den Skills](http://ask-sdk-java-javadocs.s3-website-us-west-2.amazonaws.com/)
und mal auf git geschaut wie Amazon das ganze intern testet:
[Amazon Skills auf git](https://github.com/alexa/alexa-skills-kit-sdk-for-java)
Soweit ich das sehen kann verwenden die dort immer auch eben mockito für die internen codes.
siehe z.b. [StandardSkillBuilderTest](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/ask-sdk/tst/com/amazon/ask/builder/StandardSkillBuilderTest.java)

Momentan bin ich grad dabei herauszufinden wie ich das auf unseren fall ummünze und wie ich mockito unserem projekt hinzufügen kann.

**Comment by HoferAnton** [comment]
Ok Also zur Info In der Aktuellen Version kann führt die Methode getSkill zum absturz, da anscheinend ein region code in der provider chain fehlt.

**Comment by HoferAnton** [comment]
Momentaner Stand:

1. Maven builded trotz aktualisierter dependencies.
2. Maven nimmt das Mockito plugin nicht an -> tests scheitern.
3. Aktuell liegen Beispieltests auf hoferdev unter CancelAndStopIntentHandlerTest.java.
4. ScoreKeeperStreamHandler.java wird vorerst nicht getestet.

**Comment by OneToughMonkey** [comment]
bei mir laufen die tests jetzt auch mit maven & travis... du hattest da irgendwie Junit 5 und 4 imports gemischt und eine dependency hat noch im pom gefehlt

**Comment by OneToughMonkey** [comment]
bzw. war der junit import nicht ganz ausreichend

**Comment by phiebl** [comment]
Ich persönlich würde auch sagen, dass v.a. die Anzahl der Tests sowie auch deren Sinnhaftigkeit den Vorgaben entsprechen.

**Comment by OneToughMonkey** [comment]
:100:
