### ISSUE TITLE
Score Keeper Diagramme Sprint 1

### ISSUE THREAD

**Issue by OneToughMonkey** [sweIhm-ws2018-19/skillproject-fr_13#49]
Aufgabenstellung:
- Stellen Sie für jede User Story die Lösungsidee wenn möglich als UML Diagramm (z.B. UML Klassendiagramm oder UML Sequenzdiagramm) dar
- Es kann manchmal sinnvoll sein, dass Sie die Lösungsidee zu mehreren User Stories in einem Diagramm zusammenfassen

Erweiterte eigene Zielsetzung:
- Diagramme sollen eine reellen Mehrwert für die zukünftigen Sprintphasen bieten
- Diagramme sollen aktuelle Struktur des Projekts so klar wie möglich darstellen
- Verständlichkeit und akkurate Reflektion des Sourcecodes sind höher zu bewerten als Detailgrad und Masse
- Min. 3 Diagramme werden angestrebt

**Comment by OneToughMonkey** [comment]
Habe jetzt je ein übersichtsweises [Klassendiagramm](https://raw.githubusercontent.com/sweIhm-ws2018-19/skillproject-fr_13/monkeydev/design/Sprint_1/Klassendiagramm_%C3%9Cbersicht.png) und ein [Aktivitätsdiagramm](https://raw.githubusercontent.com/sweIhm-ws2018-19/skillproject-fr_13/monkeydev/design/Sprint_1/Aktivit%C3%A4tsdiagramm_%C3%9Cbersicht.png) für den Skill gemacht.

Hätte nix dagegen, wenn noch jemand 1-2, gerne kleinere, Diagramme dazu einbringen mag, vielleicht ein Sequenzdiagramm zur Abrundung..?

**Comment by phiebl** [comment]
Review Aktivitätsdiagramm @phiebl

**Comment by phiebl** [comment]
Das Aktivitätsdiagramm "Score Keeper aufrufen" ist sehr übersichtlich angeordnet. Alle Bedingungen führen zum vorgesehenen Ereignis. Zudem wurde die Persistenz in Form eines Interfaces(UML) in das Diagramm und den Handlungsablauf des Skills integriert. Mit dem Timout/CancleAndStopIntent der zum Endpunkt führt wird die Abbruch-/Beendigungsbedingung des Skills anschaulich verwirklicht.

**Comment by phiebl** [comment]
Review Klassendiagramm @phiebl

**Comment by phiebl** [comment]
Durch das Klassendiagramm "Sprint 1" wird die Beziehung zwischen den IntentHandlern und dem RequestHandler gut deutlich. Alle Attribute und Methoden sind korrekt angegeben. Der Zusatz "PersistentAttributes" wurde gut umgesetzt, wobei die Attribute logisch und korrekt eingebunden worden sind.

**Comment by OneToughMonkey** [comment]
danke für das feedback
