### ISSUE TITLE
Professorin Zugang zur Team-Alexa Skills Console geben

### ISSUE THREAD

**Issue by OneToughMonkey** [sweIhm-ws2018-19/skillproject-fr_13#51]
Bitte Professorin unter Settings->User Permissions der Team-ASC unter dem Nutzeraccount Sumarinal eintragen, falls noch nicht geschen.

Der Amazon Account Ihrer Professorin ist 'gsocher@yahoo.com'.

**Comment by hexahepta** [comment]
Einladung wurde an die entsprechende EMail-Addresse verschickt.

**Comment by OneToughMonkey** [comment]
danke
